config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :movies do
    collection do
      get 'search'
      get 'asort'
      get 'dsort'
      get 'rsort'

    end  
  resources :reviews 
end
  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	searchkick
	belongs_to :user
    has_many :reviews
 
has_attached_file :image, styles: { medium: "300x300#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

#validates_attachment_file_name :image, matches: {matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]}
  # , default_url: "/images/:style/missing.png" // when image is missing
  #, "image/jpeg", "image/png", "image/gif"
 # do_not_validate_attachment_file_type :image
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie

	validates :movie_id, uniqueness: { scope: :user_id, message: "You've reviewed this movie!" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_one :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
 # before_action :authenticate_user!, expect: [:index, :show]
  before_action :set_rating_array
 def asort
  @movies = Movie.order(:Title)
 end

 def dsort
  @movies = Movie.order(Title: :DESC)
  end

 def search
  if params[:search].present?
    @movies = Movie.search(params[:search])
  else
    @movies = Movie.all
  end
 end   
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
   
  end

  def rsort
    @avg_review = @avg_review
    @movies = Movie.order(@sort_rating)
  end
  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
  
   if @reviews.blank?
    @avg_review = 0
   else
    @avg_review = @reviews.average(:rating).round(2)
   end
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating_array
      @movies = Movie.all
      @avg_review = []
      @has_rating = {}
    @movies.each do |movie|
      @reviews = Review.where(movie_id: movie.id).order("created_at DESC")
     
   if @reviews.blank?
    @avg_review.push(0)
   else
   @avg_review.push(@reviews.average(:rating).round(2))
   @has_rating.store(movie.id, @reviews.average(:rating).round(2))
   end
    
 end
end
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:Title, :Description, :Duration, :Actor, :Rating, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
   @review.user_id = current_user.id
   @review.movie_id = @movie.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @movie, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @movie, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

   def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse " role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in?  %>
        <% if current_user.id == 1 %>
          <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
       
       <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
      <p> <%= text_field_tag :search, params[:search], class: "form-control" %>
       <%= submit_tag "Search", name: nil, class: "btn btn-default" %> </p>
       <% end %>

 
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<script type="text/javascript">
jQuery(function($) {
  $("#sort_by").change(function() {
   $.ajax({ 
  type: 'GET',
  url: '/sort',
  data: {'order' :$('#sort_by option:selected').val()},
  success: function(data){
    window.result = data;
  } 
   
  });
})
  })
</script>

app/views/layouts/application.html.erb
-<!DOCTYPE html>
<html class="no-js">
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
 <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class:"alert alert-info") %>
  <% end %> 
<%= yield %>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :Duration %><br>
    <%= f.text_field :Duration %>
  </div>
  <div class="field">
    <%= f.label :Actor %><br>
    <%= f.text_field :Actor %>
  </div>
 
  <div class="field">
    <%= f.label :Image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/asort.html.erb
<div class="btn-group pull-right">
       <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
        A to Z <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "A to Z", asort_movies_path %></li>
        <li><%= link_to "Z to A", dsort_movies_path %></li>
        <li><%= link_to "Rating", rsort_movies_path %></li>
       
      </ul>
    </div>

<h1>Listing Movies</h1>

<div class="row">
<% i=0 %>
    <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
       </div>
       <%= link_to movie.Title, movie, class: "caption" %>
       <div class="star-rating" data-score= <%= @avg_review[i] %> > </div>
       <% i += 1   %>
        </div>
    <% end %>
 
</div>

<script>
  $('.star-rating').raty({
    path:'/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/movies/dsort.html.erb
<div class="btn-group pull-right">
       <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
        Z to A <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "A to Z", asort_movies_path %></li>
        <li><%= link_to "Z to A", dsort_movies_path %></li>
        <li><%= link_to "Rating", rsort_movies_path%></li>
      
      </ul>
    </div>

<h1>Listing Movies</h1>

<div class="row">
<% i=0 %>
    <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
       </div>
        <%= link_to movie.Title, movie, class: "caption" %>
       <div class="star-rating" data-score= <%= @avg_review[i] %> > </div>
       <% i += 1   %>
        </div>
    <% end %>
 
</div>

<script>
  $('.star-rating').raty({
    path:'/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="btn-group pull-right">
       <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
        Sort By <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "A to Z", asort_movies_path %></li>
        <li><%= link_to "Z to A", dsort_movies_path %></li>
        <li><%= link_to "Rating", rsort_movies_path %></li>
        
      </ul>
    </div>
    <h1>Listing Movies</h1>
<div class="row">
<% i=0 %>
    <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
    </div>
       <%= link_to movie.Title, movie, class: "caption" %>
       <div class="star-rating" data-score= <%= @avg_review[i] %> > </div>
       <% i += 1   %>
        </div>
    <% end %>
 
</div>
<script>
  $('.star-rating').raty({
    path:'/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/rsort.html.erb
<div class="btn-group pull-right">
       <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
        Rating <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "A to Z", asort_movies_path %></li>
        <li><%= link_to "Z to A", dsort_movies_path %></li>
        <li><%= link_to "Rating", rsort_movies_path %></li>
        <li class="divider"></li>
        <li><%= link_to "link4", "#",{:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></li>
      </ul>
    </div>

<h1>Listing Movies</h1>
<% i=0 %>
<div class="row">
    <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
       </div>
      <%= link_to movie.Title, movie, class: "caption" %>
       <span class="star-rating" data-score= <%= @avg_review[i] %> > </span>
       <% i += 1   %>
        </div>
    <% end %>
 
</div>

<script>
  $('.star-rating').raty({
    path:'/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/movies/search.html.erb
<div class="row">
    <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
       <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
       </div>
       </div>
    <% end %>
 
</div>

app/views/movies/show.html.erb
 
  <div class="container-fluid">
  <h1> <%= @movie.Title %></h1>
  <p><%= @movie.Description %></p>
  <div class="row">
    <div class="col-sm-4" >
    <%= image_tag @movie.image.url(:medium) %>
   <div class="star-rating" data-score= <%= @avg_review %> > </div>
<p>
  <strong>Duration:</strong>
  <%= @movie.Duration %>
</p>
 
<p>
  <strong>Actor:</strong>
  <%= @movie.Actor %>
</p>

<% is_exist = 0 %>
</div>
    <div class="col-sm-8" >
   
<% if @reviews.blank? %>
  <h3> No review Yet </h3>
  <% if user_signed_in?  %>
  <%= link_to "Write a review", new_movie_review_path(@movie), class:"btn btn-default" %>
   <% end
  <% else %>
  <% @reviews.each do |review| %>

    
                        <p class="caption">  <b> <%= review.user.email %></b> </p>
                           
                      
                        <h6 class="text-muted time"><div class="star-rating" data-score= <%= review.rating %> ></div></h6>
                
                <div class="post-description"> 
                     <p><%= review.comment %> </p>

                
                   <% if user_signed_in?  && current_user.id == review.user_id  %> 
                    <% is_exist = 1 %>
                     <%= link_to 'Edit', edit_movie_review_path(@movie, review.id),class: "btn btn-default" %>
                    <%= link_to 'Delete', movie_review_path(@movie, review.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
                        <% end %>

                     <% end %>
               
  
                  </div>
  

 
      </div>
      <% end %>
 </div>

 </div>
 <div clas="container">
<div class="row">

  <% if user_signed_in?  %>
  
        <% if current_user.id == 1 %>
<%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-default" %> |
<%= link_to 'Back', movies_path, class:"btn btn-default" %>
 <%= link_to 'Destroy', @movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
<% end %>
<% end %>
  </div>
 </div>
  
 
<script>
  $('.star-rating').raty({
    path:'/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  $('#star-rating').raty({
    path:'/assets/',
    scoreName: 'review[rating]',
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>


<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>